// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blcgyyhkdwwtcojnldmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsY2d5eWhrZHd3dGNvam5sZG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MzI4OTcsImV4cCI6MjA1MTMwODg5N30.jdSwpeVLq6qM39PJTCyO-ZqIt-m59G_xOj2cYJTF5kU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);